name = "juliajim"
uuid = "dfeb43dd-e7d5-4223-99c6-bbf17d8d0dc1"
version = "0.1.0"
authors = ["Nidish <nidish@iitm.ac.in>"]

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastTransformsForwardDiff = "77fa7db0-1c81-401d-9fde-3592fc42b8bc"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[sources]
FastTransformsForwardDiff = {rev = "main", url = "https://github.com/Nidish96/FastTransformsForwardDiff.jl"}

[compat]
AbstractFFTs = "1.5.0"
Accessors = "0.1.42"
Arpack = "0.5.4"
DSP = "0.8.3"
Documenter = "1.11.4"
DocumenterTools = "0.1.20"
FFTW = "1.8.1"
FastTransformsForwardDiff = "0.0.2"
ForwardDiff = "1.3.0"
Infiltrator = "1.9.1"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
MKL = "0.9.0"
Markdown = "1.11.0"
NonlinearSolve = "4.8.0"
Printf = "1.11.0"
ProgressMeter = "1.10.4"
Random = "1.11.0"
Revise = "3.8.0"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
TensorOperations = "5.3.1"
Test = "1.11.0"
ToeplitzMatrices = "0.8.5"
UnPack = "1.0.2"
